include: images/go/shell.yaml

contents:
  packages:
    - git
    - make

entrypoint:
  command: /bin/sh

cmd: ""

annotations:
  org.opencontainers.image.title: 'go-dev'
  org.opencontainers.image.description: 'Go image based on Wolfi OS'
  org.opencontainers.image.source: 'https://github.com/duyhenryer/wolfi-image/tree/main/images/go'