include: images/apko.yaml

contents:
  packages:
    - ca-certificates-bundle
    - glibc-locale-posix
    - go
    - wolfi-baselayout

accounts:
  groups:
    - groupname: go
      gid: 65532
  users:
    - username: go
      uid: 65532
      gid: 65532
  run-as: go

paths:
  - path: /go
    type: directory
    permissions: 0o755
    uid: 65532
    gid: 65532
  - path: /go/src
    type: directory
    permissions: 0o755
    uid: 65532
    gid: 65532
  - path: /go/bin
    type: directory
    permissions: 0o755
    uid: 65532
    gid: 65532

work-dir: /go/src

entrypoint:
  command: /usr/bin/go

cmd: version

annotations:
  org.opencontainers.image.title: 'go'
  org.opencontainers.image.description: 'Go image based on Wolfi OS'
  org.opencontainers.image.source: 'https://github.com/duyhenryer/wolfi-image/tree/main/images/go'