include: images/golang/shell.yaml

contents:
  packages:
    - git
    - make

cmd: ""

annotations:
  org.opencontainers.image.title: 'golang-dev'
  org.opencontainers.image.description: 'Golang image based on Wolfi OS'
  org.opencontainers.image.source: 'https://github.com/duyhenryer/wolfi-image/tree/main/images/golang'