include: images/apko.yaml

contents:
  packages:
    - ca-certificates-bundle
    - glibc-locale-posix
    - nodejs
    - wolfi-baselayout

entrypoint:
  command: /usr/sbin/node

cmd: --help

annotations:
  org.opencontainers.image.title: 'node'
  org.opencontainers.image.description: 'Node image based on Wolfi OS'
  org.opencontainers.image.source: 'https://github.com/duyhenryer/wolfi-image/tree/main/images/node'