include: images/apko.yaml

contents:
  packages:
    - ca-certificates-bundle
    - glibc-locale-posix
    - python
    - python-pip
    - wolfi-baselayout
    - git
    - curl
    - wget

entrypoint:
  command: /usr/bin/python

annotations:
  org.opencontainers.image.title: 'python'
  org.opencontainers.image.description: 'Python development image based on Wolfi OS'
  org.opencontainers.image.source: 'https://github.com/duyhenryer/wolfi-images/tree/main/images/python'