name: node

on:
  schedule:
    - cron: "00 01 * * 1-5"
  push:
    branches:
      - 'main'
    paths:
      - .github/workflows/node.yaml
      - 'images/node/*.yaml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
  security-events: write
  actions: read

jobs:
  publish:
    strategy:
      matrix:
        version: [latest, "23", "22", "20"]
        variant: [prod, shell, dev]
    name: ${{ matrix.version }}${{ matrix.variant == 'shell' && '-shell' || matrix.variant == 'dev' && '-dev' || '' }}
    uses: './.github/workflows/release.yaml'
    with:
      tag: ${{ matrix.version }}${{ matrix.variant == 'shell' && '-shell' || matrix.variant == 'dev' && '-dev' || '' }}
      target: ${{ matrix.variant }}
      packages: >-
        ${{ matrix.version != 'latest' && format('nodejs~{0}', matrix.version) || '' }}
    secrets: inherit